/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DLL;

//import SLL.*;

/**
 *
 * @author Fakhry
 */
public class DLLGUI extends javax.swing.JFrame {

    /**
     * Creates new form SLLGUI
     */
    public DLLGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        fieldData = new javax.swing.JTextField();
        fieldIndex = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listOperasi = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fieldData2 = new javax.swing.JTextField();
        btProses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAreaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        jLabel1.setText("Data1");

        jLabel2.setText("Index");

        listOperasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Insert First", "Insert Last", "Insert After", "Insert at Index", "Delete First", "Delete Last", "Delete Value", "Delete After", "Delete at Index", "Find Node", "Sort (Max -> Min)", "Sort (Min -> Max)" }));
        listOperasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOperasiActionPerformed(evt);
            }
        });

        jLabel3.setText("Data 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listOperasi, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(fieldData2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listOperasi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(fieldData2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        btProses.setText("Proses");
        btProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btProses, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btProses, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        txAreaOutput.setColumns(20);
        txAreaOutput.setRows(5);
        jScrollPane1.setViewportView(txAreaOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listOperasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOperasiActionPerformed
        // TODO add your handling code here:
        if (listOperasi.getSelectedIndex() == 0 || //insert first
            listOperasi.getSelectedIndex() == 1 || //insert last
            listOperasi.getSelectedIndex() == 6 || //delete value
            listOperasi.getSelectedIndex() == 7 || //delete after
            listOperasi.getSelectedIndex() == 9) { //find node
            fieldIndex.setEnabled(false);
            fieldData.setEnabled(true);
            fieldData2.setEnabled(false);
        }else if(listOperasi.getSelectedIndex() == 4 || //delete first
                listOperasi.getSelectedIndex() == 5 || //delete last
                listOperasi.getSelectedIndex() == 10 || //sort
                listOperasi.getSelectedIndex() == 11){ //sort
            fieldIndex.setEnabled(false);
            fieldData.setEnabled(false);
            fieldData2.setEnabled(false);
        }else if( listOperasi.getSelectedIndex() == 8){ //delete at index
            fieldIndex.setEnabled(true);
            fieldData.setEnabled(false);
            fieldData2.setEnabled(false);
        }else if(listOperasi.getSelectedIndex() == 2){ //insert after
            fieldIndex.setEnabled(false);
            fieldData.setEnabled(true);
            fieldData2.setEnabled(true);
        }else if(listOperasi.getSelectedIndex() == 3){ //insert at index
            fieldIndex.setEnabled(true);
            fieldData.setEnabled(true);
            fieldData2.setEnabled(false);
        }
        else{
            fieldIndex.setEnabled(true);
            fieldData.setEnabled(true);
            fieldData2.setEnabled(true);
        }
    }//GEN-LAST:event_listOperasiActionPerformed

    private DoubleLinkedList dll = new DoubleLinkedList();
    private void btProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProsesActionPerformed
        // TODO add your handling code here:
        int selected = listOperasi.getSelectedIndex();
        if(selected == 0){ //insert first
            dll.InsertFirst(Byte.parseByte(fieldData.getText()));
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 1){ //insert last
            dll.InsertLast(Byte.parseByte(fieldData.getText()));
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 2){ //insert after
            dll.InsertAfter(Byte.parseByte(fieldData.getText()), Byte.parseByte(fieldData2.getText()));
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 3){ //insert at index
            dll.InsertAtIndex(Integer.parseInt(fieldIndex.getText()), Byte.parseByte(fieldData.getText()));
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 4){ //delete first
            dll.DeleteFirst();
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 5){ //delete last
            dll.DeleteLast();
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 6){ //delete Value
            dll.DeleteValue(Byte.parseByte(fieldData.getText()));
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 7){ //delete after
            dll.DeleteAfter(Byte.parseByte(fieldData.getText()));
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 8){ //delete at index
            dll.DeleteAtIndex(Byte.parseByte(fieldIndex.getText()));
            txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 9){ //Find Node
            String hasil = dll.FindNodeGUI(Byte.parseByte(fieldData.getText()));
            txAreaOutput.append(hasil+" \n");
        }else if(selected == 10){ //Sort Max to Min
           dll.SortMm();
           txAreaOutput.append(dll.toString()+" \n");
        }else if(selected == 11){ //sort min to max
           dll.Sort();
           txAreaOutput.append(dll.toString()+" \n");
        }
        
    }//GEN-LAST:event_btProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DLLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DLLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DLLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DLLGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DLLGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProses;
    private javax.swing.JTextField fieldData;
    private javax.swing.JTextField fieldData2;
    private javax.swing.JTextField fieldIndex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listOperasi;
    private javax.swing.JTextArea txAreaOutput;
    // End of variables declaration//GEN-END:variables
}
